#' @useDynLib DifferentialRegulation, .registration=TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom Matrix readMM
#' @importFrom Matrix t
#' @importFrom Matrix Matrix
#' @importFrom Matrix rowSums
#' @importFrom Matrix colSums
#' @importFrom doRNG '%dorng%'
#' @importFrom foreach '%dopar%'
#' @importFrom data.table fread
#' @importFrom MASS ginv
#' @importFrom methods is
#' @importFrom foreach foreach
#' @importFrom parallel makeCluster
#' @importFrom parallel stopCluster
#' @importFrom doParallel registerDoParallel
#' @importFrom doParallel stopImplicitCluster
#' @importFrom SingleCellExperiment SingleCellExperiment
#' @importFrom SingleCellExperiment colData
#' @importFrom SummarizedExperiment assays
#' @importFrom BANDITS prior_precision
#' @importFrom stats p.adjust
#' @importFrom stats cov
#' @importFrom stats pchisq
#' @importFrom stats window
#' @importFrom stats lm
#' @importFrom stats residuals
#' @importFrom stats sd
#' @importFrom stats ar
#' @importFrom stats density
NULL