#' @useDynLib DifferentialRegulation, .registration=TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom Matrix readMM
#' @importFrom Matrix t
#' @importFrom Matrix Matrix
#' @importFrom Matrix rowSums
#' @importFrom Matrix colSums
#' @importFrom doRNG '%dorng%'
#' @importFrom foreach '%dopar%'
#' @importFrom data.table fread
#' @importFrom data.table last
#' @importFrom MASS ginv
#' @importFrom methods is
#' @importFrom foreach foreach
#' @importFrom parallel clusterCall
#' @importFrom parallel makeCluster
#' @importFrom parallel stopCluster
#' @importFrom parallel parLapply
#' @importFrom doParallel registerDoParallel
#' @importFrom doParallel stopImplicitCluster
#' @importFrom SingleCellExperiment SingleCellExperiment
#' @importFrom SingleCellExperiment colData
#' @importFrom SummarizedExperiment assays
#' @importFrom SummarizedExperiment rowData
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom BANDITS prior_precision
#' @importFrom stats p.adjust
#' @importFrom stats cov
#' @importFrom stats pchisq
#' @importFrom stats window
#' @importFrom stats lm
#' @importFrom stats residuals
#' @importFrom stats sd
#' @importFrom stats ar
#' @importFrom stats density
#' @importFrom stats median
#' @importFrom stats var
#' @importFrom stats qnorm
#' @importFrom tximport tximport
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 ylim
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_vline
#' @importFrom gridExtra grid.arrange
#' @importFrom tximport tximport
NULL